#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
| @author ekajayanagara
|--------------------------------------------------------------------------
|
*/
require_once __DIR__ . "//vendor//autoload.php";
spl_autoload_register(function ($class) {
	$class = explode("\\", $class);
	$class = end($class);
	if (file_exists(__DIR__ . "/system/filesystem/" . $class . ".php")) {
		require_once __DIR__ . "/system/filesystem/" . $class . ".php";
	}
	return false;
});

/*
|--------------------------------------------------------------------------
| Register Class Loader
| @author ekajayanagara
|--------------------------------------------------------------------------
|
*/

use Console\App\Commands\AuthorCommand;
use Symfony\Component\Console\Application;
use Console\App\Commands\TestCommand;
use Console\App\Commands\ClearcacheCommand;
use Console\App\Commands\DeskriptionCommand;
use Console\App\Commands\EnvirotmentCommand;
use Console\App\Commands\MakeControllerCommand;
use Console\App\Commands\MakeLibrariesCommand;
use Console\App\Commands\MakeModelsCommand;
use Console\App\Commands\MakeViewCommand;
use Console\App\Commands\ServerCommand;
use Console\App\Commands\CopyEnvirotmentCommand;
use Console\App\Commands\MakeMigrationCommand;
use Console\App\Commands\MigrationHelpCommnand;
use Console\App\Commands\MigrationCommnand;
use Console\App\Commands\RollbackMigrationCommnand;
use Console\App\Commands\MakeSeedMigrationCommand;
use Console\App\Commands\SeedRunMigrationCommand;
use Console\App\Commands\UnitTestBootsrapCommnad;
use Console\App\Commands\UnitTestRunCommand;
use Console\App\Commands\UnitTestBuildCommnad;
use Console\App\Commands\UnitTestScenenarioCommand;

/*
|--------------------------------------------------------------------------
| Register new object call
| @author ekajayanagara
|--------------------------------------------------------------------------
|
*/


$app = new Application('mini mvc nagara', '4.0.4');
$app->add(new TestCommand());
$app->add(new ClearcacheCommand());
$app->add(new MakeControllerCommand());
$app->add(new MakeLibrariesCommand());
$app->add(new MakeModelsCommand());
$app->add(new MakeViewCommand());
$app->add(new AuthorCommand());
$app->add(new DeskriptionCommand());
$app->add(new ServerCommand());
$app->add(new EnvirotmentCommand());
$app->add(new CopyEnvirotmentCommand());
$app->add(new MakeMigrationCommand());
$app->add(new MigrationHelpCommnand());
$app->add(new MigrationCommnand());
$app->add(new RollbackMigrationCommnand());
$app->add(new MakeSeedMigrationCommand());
$app->add(new SeedRunMigrationCommand());
$app->add(new UnitTestBootsrapCommnad());
$app->add(new UnitTestRunCommand());
$app->add(new UnitTestBuildCommnad());
$app->add(new UnitTestScenenarioCommand());

$app->run();
