#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
| @author ekajayanagara
|--------------------------------------------------------------------------
|
*/
require_once __DIR__ . "//vendor//autoload.php";
spl_autoload_register(function ($class) {
	$class = explode("\\", $class);
	$class = end($class);
	if (file_exists(__DIR__ . "/system/filesystem/" . $class . ".php")) {
		require_once __DIR__ . "/system/filesystem/" . $class . ".php";
	}
	return false;
});

/*
|--------------------------------------------------------------------------
| Register Class Loader
| @author ekajayanagara
|--------------------------------------------------------------------------
|
*/

use Console\App\Commands\AuthorCommand;
use Symfony\Component\Console\Application;
use Console\App\Commands\TestCommand;
use Console\App\Commands\ClearcacheCommand;
use Console\App\Commands\DeskriptionCommand;
use Console\App\Commands\EnvirotmentCommand;
use Console\App\Commands\MakeControllerCommand;
use Console\App\Commands\MakeLibrariesCommand;
use Console\App\Commands\MakeModelsCommand;
use Console\App\Commands\MakeViewCommand;
use Console\App\Commands\ServerCommand;
use Console\App\Commands\CopyEnvirotmentCommand;


/*
|--------------------------------------------------------------------------
| Register new object call
| @author ekajayanagara
|--------------------------------------------------------------------------
|
*/


$app = new Application('mini mvc nagara', '2.0.11');
$app->add(new TestCommand());
$app->add(new ClearcacheCommand());
$app->add(new MakeControllerCommand());
$app->add(new MakeLibrariesCommand());
$app->add(new MakeModelsCommand());
$app->add(new MakeViewCommand());
$app->add(new AuthorCommand());
$app->add(new DeskriptionCommand());
$app->add(new ServerCommand());
$app->add(new EnvirotmentCommand());
$app->add(new CopyEnvirotmentCommand());
$app->run();